/* Synthetic demo records only. Not real providers and not available for booking. */
window.ATLAS_DEMO_RECORDS=[
 {id:'DEMO-TERAPISTA-COMP-LECCE-01',entity_type:'professional',name:'Professionista demo — Terapia comportamentale Lecce',services:['terapia comportamentale','intervento comportamentale'],professional_role:'terapista',specializations:['comportamentale','autismo'],population:{age_min:2,age_max:18},access:{city:'Lecce',province:'Lecce',online:true,setting:'private',appointment_modes:['in_person','online']},availability:{status:'accepting'},verification:{status:'self_declared'},cost:{min:45,max:80,currency:'EUR'}},
 {id:'DEMO-TERAPISTA-OCC-NAPOLI-01',entity_type:'professional',name:'Professionista demo — Terapia occupazionale Napoli',services:['terapia occupazionale'],professional_role:'terapista',specializations:['occupazionale','autonomia'],population:{age_min:2,age_max:18},access:{city:'Napoli',province:'Napoli',online:false,setting:'private',appointment_modes:['in_person']},availability:{status:'accepting'},verification:{status:'self_declared'},cost:{min:45,max:80,currency:'EUR'}},
 {id:'DEMO-LOGO-NAPOLI-01',entity_type:'professional',name:'Professionista demo — Logopedia Napoli',services:['logopedia','comunicazione'],professional_role:'logopedista',specializations:['linguaggio','comunicazione'],population:{age_min:2,age_max:18},access:{city:'Napoli',province:'Napoli',online:true,setting:'private',appointment_modes:['in_person','online']},availability:{status:'accepting'},verification:{status:'self_declared'},cost:{min:40,max:70,currency:'EUR'}},
 {id:'DEMO-LOGO-LECCE-01',entity_type:'professional',name:'Professionista demo — Logopedia Lecce',services:['logopedia','comunicazione'],professional_role:'logopedista',specializations:['linguaggio','comunicazione'],population:{age_min:2,age_max:18},access:{city:'Lecce',province:'Lecce',online:true,setting:'private',appointment_modes:['in_person','online']},availability:{status:'accepting'},verification:{status:'self_declared'},cost:{min:40,max:70,currency:'EUR'}},
 {id:'DEMO-CENTRO-01',entity_type:'center',name:'Centro demo — Neurodivergenze',services:['valutazione','logopedia','supporto famiglia'],professional_role:'centro',specializations:['autismo','neurodivergenze'],population:{age_min:0,age_max:25},access:{city:'Napoli',province:'Napoli',online:false,setting:'mixed',appointment_modes:['in_person']},availability:{status:'waitlist'},verification:{status:'document_checked',source:'demo-fixture'},cost:{min:0,max:100,currency:'EUR'}},
 {id:'DEMO-NPI-01',entity_type:'professional',name:'Professionista demo — NPI',services:['valutazione','seconda opinione'],professional_role:'neuropsichiatra infantile',specializations:['neuropsichiatria infantile'],population:{age_min:0,age_max:18},access:{city:'Lecce',province:'Lecce',online:true,setting:'private',appointment_modes:['in_person','online']},availability:{status:'unknown'},verification:{status:'stale'},cost:{min:80,max:150,currency:'EUR'}}
];
