(function(){'use strict';
const form=document.getElementById('atlas-form'),result=document.getElementById('result'),feedback=document.getElementById('feedback');
function val(n){const e=form.elements[n];return e?e.value:''} function checks(n){return Array.from(form.querySelectorAll('input[name="'+n+'"]:checked')).map(x=>x.value)}
function buildInput(){return window.AtlasNormalizer.normalizeQuestionnaire({phase:val('phase'),need:val('need'),resources:checks('resources'),resourcesOther:val('resourcesOther'),gaps:checks('gaps'),barriers:checks('barriers'),intent:{goal:val('goal')},comune:val('comune'),provincia:val('provincia'),distance:val('distance'),online:!!form.elements.online.checked})}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function restart(){result.hidden=true;feedback.classList.add('hidden');form.hidden=false;window.scrollTo({top:0,behavior:'smooth'})}
function render(profile){const r=window.AtlasResponse.buildResponse(profile);const c=r.constraints.length?'<p><strong>Ricerca:</strong> '+esc(r.constraints.join(' · '))+'</p>':'';const n=r.note?'<p class="note">'+esc(r.note)+'</p>':'';result.innerHTML='<div class="result-card"><div class="eyebrow">Abbiamo capito</div><h2>Il bisogno principale sembra essere quello di <span>'+esc(r.summary)+'</span>.</h2><div class="eyebrow">Il prossimo passo</div><p>'+esc(r.nextStep)+'.</p>'+c+'<div class="eyebrow">Possiamo aiutarti</div><p>'+esc(r.help)+'</p>'+n+'<button id="restart" class="btn secondary" type="button">Modifica le risposte</button><p class="footer">'+esc(r.disclaimer)+'</p></div>';document.getElementById('restart').onclick=restart;form.hidden=true;result.hidden=false;feedback.classList.remove('hidden');result.scrollIntoView({behavior:'smooth'})}
form.addEventListener('submit',e=>{e.preventDefault();if(!form.checkValidity()){form.reportValidity();return}try{render(window.AtlasEngine.buildProfile(buildInput()))}catch(err){result.hidden=false;form.hidden=true;feedback.classList.add('hidden');result.innerHTML='<div class="result-card"><h2>Si è verificato un problema.</h2><p>Il test non è riuscito a interpretare le risposte. Questa sessione non viene considerata valida.</p><button id="restart" class="btn secondary" type="button">Torna al questionario</button></div>';document.getElementById('restart').onclick=restart;console.error(err)}});
document.getElementById('copyFeedback').onclick=async()=>{const t='Atlas Public Test\nComprensione: '+val('fit')+'\nProssimo passo più chiaro: '+val('clarity')+'\nCommento: '+document.getElementById('feedbackText').value;try{await navigator.clipboard.writeText(t);document.getElementById('copyFeedback').textContent='Feedback copiato ✓'}catch(e){window.prompt('Copia questo testo:',t)}};
})();
